### ISSUE TITLE
Transposition of "physical state" vs "logical state"

### ISSUE THREAD

**Issue by paulw11** [sgentry/elkmon#1]
It seems like the *physical state* and *logical state* reported in the `zoneChangeUpdate` (and other zone-related messages) are reversed.   The physical state should refer to the electrical state of the zone (open, shorted, EOL) while the logical state is the state of the zone in terms of the alarm (Normal, bypassed, violated).

For example, for a zone of type NC, a physical state of "Open" is a logical state of "Violated" while for an NO zone a physical state of "Open" is logical state of "Normal".

I realise that addressing this is a "breaking change", so I am not sure if you want to action it.

**Comment by sgentry** [comment]
Thanks for reporting this! I've checked-in an update to address this issue. Feel free to review if you will. I want to test it a little more before I release version 1.0.0 with this change.

**Comment by sgentry** [comment]
This was fixed in commit 8542a384f47d32f605dce77958d431e9b720c4fa
