### ISSUE TITLE
requestTextDescriptionAll times out on low power devices

### ISSUE THREAD

**Issue by paulw11** [sgentry/elkmon#2]
When running on a Raspberry Pi, `requestTextDescriptionAll` times out when retrieving large amounts of text and there is no parameter to specify a larger timeout.

**Comment by sgentry** [comment]
I just noticed you reported a few issues. Guess notifications are not turned on for myself. I'll take a closer look this week but this one should be an easy fix.

**Comment by paulw11** [comment]
Thanks.

**Comment by sgentry** [comment]
Added an optional parameter to specify the timeout. It now defaults to 15s. 209d68a28e3ea5e8089555a49506eb331998e9e3
